trigger:
- master  # or your main branch name

steps:
  # Checkout the repository
  - checkout: self
    displayName: 'Checkout Source'

  # Run Blacklock Code Scanner
  - script: |
      docker pull blacklocksec/code-scanner:latest
      docker run --rm -v $(Build.SourcesDirectory):/app -e SONAR_PROJECTKEY='not-azure' -e SONAR_HOST_URL=$(SONAR_HOST_URL) -e SONAR_TOKEN=$(SONAR_TOKEN) blacklocksec/code-scanner:latest
    displayName: 'Run Blacklock Code Scanner'
    env:
      SONAR_HOST_URL: $(SONAR_HOST_URL)
      SONAR_TOKEN: $(SONAR_TOKEN)

  # Prepare Analysis Configuration
  - task: SonarQubePrepare@6
    inputs:
      SonarQube: 'main_server'
      scannerMode: 'Other'
      extraProperties: 'sonar.projectKey=not-azure'

  # Publish Quality Gate Result
  - task: SonarQubePublish@6
    inputs:
      pollingTimeoutSec: '300'
